
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: iceknight
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    flyway:
      baseline-on-migrate: true
      enabled: true
      out-of-order: true
      placeholder-prefix: '#['
      placeholder-replacement: true
      placeholder-suffix: ']'
      placeholders:
        username: ${spring.datasource.username}